SNovy-88/journey

src/main/webapp/searchResultList.jsp

Result page small changes

---

src/main/webapp/hikeDetails.jsp

fixed DB loading Hike details page

---

src/main/webapp/hikeDetails.jsp

fixed the recommended months js function so ranges from dez to march also work, (12-15 in database)

Fix months range

---

src/main/webapp/CSS/resultList.css
src/main/webapp/searchResultList.jsp

leere searchbar funktioniert zeigt immer alle hikes an, text wenn keine suchergebnisse, searchbar bei suche

Search design

---

src/main/java/at/fhv/journey/servlets/createPageServlet.java

changed createPageServlet only

added mockdata for field month, author and date

---

src/main/java/at/fhv/journey/servlets/createPageServlet.java
src/main/webapp/createHike.jsp

fixed unsaved changes-popup bug, when creating a hike

added success popup

---

src/main/webapp/CSS/hikeDetails.css
src/main/webapp/CSS/resultList.css
src/main/webapp/hikeDetails.jsp

die Größe der Icons wurde geändert

updated css and hikeDetails page

---

src/main/java/at/fhv/journey/servlets/createPageServlet.java
src/main/webapp/createHike.jsp

attributes of stepper 2 are now being saved in database correctly.

Updating servlet stepper2 create page

---

src/main/java/at/fhv/journey/servlets/createPageServlet.java

Solved getPart-error in createPageServlet

---

src/main/java/at/fhv/journey/model/Hike.java

Added one line for Hike_id generator

Implemented Generate Hike Id

---

src/main/webapp/CSS/loadingSpinner.css
src/main/webapp/JS/loadingSpinner.js
src/main/webapp/JS/search.js
src/main/webapp/loadingSpinner.jsp
src/main/webapp/search.jsp

Loading Spinner that shows up while the hikes for the Resultlist Page are loaded.

Loading spinner

---

src/main/webapp/JS/createHike.js

changed 1 method in the validation function from parseInt() to parseFloat()

changed parseInt method to parseFloat

---

pom.xml
src/main/java/at/fhv/journey/servlets/detailPageServlet.java
src/main/webapp/JS/hikeDetails.js
src/main/webapp/hikeDetails.jsp

Added map to hikeDetail.jsp

---

src/main/java/at/fhv/journey/servlets/detailPageServlet.java
src/main/webapp/CSS/hikeDetails.css
src/main/webapp/JS/createHikeMap.js
src/main/webapp/createHike.jsp
src/main/webapp/hikeDetails.jsp

Add description when adding a waypoint in createHike.jsp. Also added accordion-like description element to hikeDetails.jsp.

Added waypoint descriptions

---

src/main/webapp/hikeDetails.jsp

Get first coord instead of last in route for weather forecast

Weather forecast changes

---

src/main/webapp/CSS/createHike.css
src/main/webapp/JS/createHike.js
src/main/webapp/JS/createHikeMap.js
src/main/webapp/JS/createHikeUploadMap.js
src/main/webapp/JS/fetchRoute.js
src/main/webapp/JS/hikeDetailsMap.js
src/main/webapp/createHike.jsp
src/main/webapp/hikeDetails.jsp

changed routing fetching to fetch GeoJSON instead of URL fetching in order to have values Duratio, Distance and Height Difference automatically calculated.

Ravamp of Routing API (GeoJSON) + Automatic calculation values

---

src/main/webapp/CSS/login.css
src/main/webapp/login.jsp
src/main/webapp/success.jsp

fixed the bug (back-button on login page) + minor changes on the success page (background color + text decorations + icon)

Login back button

---

src/main/webapp/JS/hikeDetailsMap.js
src/main/webapp/hikeDetails.jsp

Added elevation profile chart to hikeDetail.jsp

Elevation profile

---

pom.xml
src/main/java/at/fhv/journey/model/User.java
src/main/java/at/fhv/journey/servlets/loginPageServlet.java

the attribute names were adjusted in the user class and a comparison was added in the loginPageServlet, where the entered password is hashed and compared with the stored hashed password in the database

hashing algorithm - passwords

---

pom.xml
src/main/java/at/fhv/journey/hibernate/broker/CommentBrokerJPA.java
src/main/java/at/fhv/journey/hibernate/broker/UserBrokerJPA.java
src/main/java/at/fhv/journey/hibernate/facade/DatabaseFacade.java
src/main/java/at/fhv/journey/hibernate/facade/IdbFacadeJPA.java
src/main/java/at/fhv/journey/model/Comment.java
src/main/java/at/fhv/journey/model/Hike.java
src/main/java/at/fhv/journey/model/User.java
src/main/java/at/fhv/journey/servlets/detailPageServlet.java
src/main/java/at/fhv/journey/servlets/loginPageServlet.java
src/main/webapp/CSS/hikeDetails.css
src/main/webapp/hikeDetails.jsp

- Kommentar Bereich erstellt
- Kommentare können erstellt werden
- Kommentare des Hikes werden angezeigt
- Kommentarfeld darf nicht leer sein zum erstellen
- Man muss eingelogged sein sonst wird man zur Log-in seite weitergeleitet (Wie bei createHike nur mit einer Alert message)

Comment detail page

---

src/main/java/at/fhv/journey/servlets/detailPageServlet.java
src/main/webapp/JS/createHike.js
src/main/webapp/JS/createHikeMap.js
src/main/webapp/JS/createHikeUploadMap.js
src/main/webapp/JS/hikeDetailsMap.js
src/main/webapp/createHike.jsp

- you now need to add at least two waypoints to map to get validation to next step
- success page redirects you to search.jsp now after closing pop-up
- removed "wpt" section from GPX. Now only "trkpt"
- changed coordinate list to bootstrap coordinate table with wpt-type and wpt-description
- API-errors in automatic calculation of values are now being caught by replacing "NaN"-value to zero (0)

Minor bug fixes and subtle changes in createHike.jsp (see desc)

---

src/main/webapp/CSS/login.css
src/main/webapp/login.jsp

- had to delete the goBack() function because it caused some problems => loginValidation :(
- some adjustments in the login.css
- you will now be redirected directly to the index.jsp when you click on the back button, I tried to fix that with the history.back() function but unfortunately it didn't work

update backButton login page

---

src/main/java/at/fhv/journey/hibernate/facade/DatabaseFacade.java
src/main/java/at/fhv/journey/servlets/registerPageServlet.java
src/main/webapp/CSS/register.css
src/main/webapp/JS/register.js
src/main/webapp/login.jsp
src/main/webapp/register.jsp

register page with the following functionalities:
- able to enter username, email and password
- if email already exists in the database - error modal otherwise success modal
- in the success modal you should click on the "sign-in" button to log in with your created account

Register page

---

src/main/java/at/fhv/journey/servlets/detailPageServlet.java
src/main/webapp/JS/hikeDetailsMap.js

Fixed xml-parsing bug:
- Empty tags have alerted a NullPointerException
- "&"-symbol bug

XML-parsing bug
